import './globals.css';
import { Inter, Shojumaru } from 'next/font/google';


const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter' 
});

const shojumaru = Shojumaru({  
weight: '400',
subsets: ['latin'],
variable: '--font-shojumaru'
});



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
};

export default function RootLayout({ children })
{
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} ${shojumaru.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
